repos:
  - repo: https://github.com/ambv/black
    rev: stable
    hooks:
      - id: black
        args: [ --exclude=^migrations/ ] # skip migrations

  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v1.2.1  # Use the ref you want to point at
    hooks:
      - id: check-merge-conflict
      - id: end-of-file-fixer
      - id: flake8
        args: [ --max-line-length=100, --max-complexity=10, '--ignore="E722, E203, E266, E501, W503, F403, F401"',--exclude=*/migrations/* ]

  - repo: https://github.com/pycqa/pylint
    rev: pylint-2.4.4
    hooks:
      - id: pylint
        args: [ --max-line-length=100, "--disable=C0103,C0415,E0401,R0903,W0613,W0703" ]
