# Generated by Django 3.1.1 on 2020-09-30 07:44

import api.users.usermanagers
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("auth", "0012_alter_user_first_name_max_length"),
    ]

    operations = [
        migrations.CreateModel(
            name="User",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("password", models.CharField(max_length=128, verbose_name="password")),
                (
                    "last_login",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="last login"
                    ),
                ),
                (
                    "status",
                    models.IntegerField(
                        choices=[(0, "pending"), (1, "activated"), (-1, "blocked")],
                        default=0,
                    ),
                ),
                (
                    "email",
                    models.EmailField(
                        max_length=254, unique=True, verbose_name="email address"
                    ),
                ),
                (
                    "full_name",
                    models.CharField(
                        blank=True, max_length=128, verbose_name="full name"
                    ),
                ),
                ("is_staff", models.BooleanField(default=False, verbose_name="staff")),
                (
                    "is_superuser",
                    models.BooleanField(default=False, verbose_name="super user"),
                ),
                (
                    "verification_code",
                    models.CharField(blank=True, default="", max_length=6, null=True),
                ),
                (
                    "provider",
                    models.CharField(
                        choices=[("SO", "Social"), ("DE", "System Generated")],
                        default="DE",
                        max_length=2,
                    ),
                ),
                ("social_token", models.TextField(blank=True, null=True)),
                ("created_on", models.DateTimeField(auto_now_add=True)),
                ("modified_on", models.DateTimeField(auto_now=True)),
                (
                    "groups",
                    models.ManyToManyField(
                        blank=True,
                        help_text="The groups this user belongs to. A user will get all permissions granted to each of their groups.",
                        related_name="user_set",
                        related_query_name="user",
                        to="auth.Group",
                        verbose_name="groups",
                    ),
                ),
                (
                    "user_permissions",
                    models.ManyToManyField(
                        blank=True,
                        help_text="Specific permissions for this user.",
                        related_name="user_set",
                        related_query_name="user",
                        to="auth.Permission",
                        verbose_name="user permissions",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
            managers=[
                ("objects", api.users.usermanagers.UserManager()),
            ],
        ),
    ]
