"""User Model Migrations Created"""
# Generated by Django 3.1.1 on 2020-11-09 22:41

import api.users.usermanagers
from django.db import migrations, models
import pgcrypto.fields


class Migration(migrations.Migration):
    """User Model Migrations Created"""
    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(
                    auto_created=True, primary_key=True,
                    serialize=False, verbose_name='ID')
                 ),
                ('password', models.CharField(
                    max_length=128, verbose_name='password')
                 ),
                ('last_login', models.DateTimeField(
                    blank=True, null=True,
                    verbose_name='last login')
                 ),
                ('created_on', models.DateTimeField(
                    auto_now_add=True)
                 ),
                ('modified_on', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(
                    choices=[('PENDING', 'pending'),
                             ('ACTIVATED', 'activated'),
                             ('BLOCKED', 'blocked')],
                    default='PENDING', max_length=10)
                 ),
                ('email', pgcrypto.fields.EncryptedEmailField(
                    charset='utf-8', check_armor=True, cipher='aes',
                    unique=True, verbose_name='Email Address',
                    versioned=False)
                 ),
                ('full_name', models.CharField(
                    blank=True, max_length=128,
                    verbose_name='Full Name')
                 ),
                ('is_staff', models.BooleanField(
                    default=False, verbose_name='Is Staff')
                 ),
                ('is_superuser', models.BooleanField(
                    default=False, verbose_name='Is Super User')
                 ),
                ('verification_code', models.CharField(
                    blank=True, default=None, max_length=6,
                    null=True, verbose_name='Verification Code')
                 ),
                ('provider', models.CharField(
                    choices=[('SO', 'Social'),
                             ('DE', 'System Generated')],
                    default='DE', max_length=2)
                 ),
                ('groups', models.ManyToManyField(
                    blank=True, help_text='The groups this user belongs to. '
                                          'A user will get all permissions granted to '
                                          'each of their groups.', related_name='user_set',
                    related_query_name='user', to='auth.Group',
                    verbose_name='groups')
                 ),
                ('user_permissions', models.ManyToManyField(
                    blank=True, help_text='Specific permissions for this user.',
                    related_name='user_set',
                    related_query_name='user',
                    to='auth.Permission',
                    verbose_name='user permissions')
                 ),
            ],
            options={
                'abstract': False,
            },
            managers=[
                ('objects', api.users.usermanagers.UserManager()),
            ],
        ),
    ]
