# Generated by Django 3.1.1 on 2020-10-23 10:51

from django.db import migrations
import hashid_field.field


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='id',
            field=hashid_field.field.HashidAutoField(
                alphabet='abcdefghijklmnopqrstuvwxyzABCDEFGHIJ'
                         'KLMNOPQRSTUVWXYZ1234567890',
                min_length=7, primary_key=True, serialize=False),
        ),
    ]
