# Generated by Django 3.1.1 on 2020-11-05 21:58
"""hash ID mifration"""

from django.db import migrations
import hashid_field.field


class Migration(migrations.Migration):
    """hash ID mifration"""

    dependencies = [
        ('users', '0002_auto_20201105_0920'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='id',
            field=hashid_field.field.HashidAutoField(
                alphabet='abcdefghijklmnopqrstuvwxyzABCDEF'
                         'GHIJKLMNOPQRSTUVWXYZ1234567890',
                min_length=7, primary_key=True, serialize=False),
        ),
    ]
