# Generated by Django 3.1.2 on 2020-11-02 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0002_auto_20201023_0620"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="is_staff",
            field=models.BooleanField(default=False, verbose_name="Is Staff"),
        ),
        migrations.AlterField(
            model_name="user",
            name="is_superuser",
            field=models.BooleanField(default=False, verbose_name="Is Super User"),
        ),
        migrations.AlterField(
            model_name="user",
            name="status",
            field=models.CharField(
                choices=[
                    ("PENDING", "pending"),
                    ("ACTIVATED", "activated"),
                    ("BLOCKED", "blocked"),
                ],
                default="PENDING",
                max_length=10,
            ),
        ),
    ]
