# Generated by Django 3.1.1 on 2020-11-11 11:17
"""Registration Email Tracking table"""
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    """Migration to keep track of Registration-EMAIL Sending  status"""
    dependencies = [
        ('users', '0002_crypto_extension'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmailStatus',
            fields=[
                ('id', models.AutoField(
                    auto_created=True, primary_key=True,
                    serialize=False, verbose_name='ID')
                 ),
                ('email_status', models.CharField(
                    choices=[('FA', 'Fail'), ('SU', 'Success'), ('PE', 'Pending')],
                    default='PE', max_length=2, verbose_name='Email Status')
                 ),
                ('user_email', models.ForeignKey(
                    on_delete=django.db.models.deletion.CASCADE,
                    to=settings.AUTH_USER_MODEL)
                 ),
            ],
        ),
    ]
