"""custom migration added to install CryptoExtension extension postgres"""
# Generated by Django 3.1.1 on 2020-11-08 17:44

from django.contrib.postgres.operations import CryptoExtension

from django.db import migrations

class Migration(migrations.Migration):
    """Adding CryptoExtension postgres"""

    dependencies = [
        ('users', '0002_auto_20201105_0920'),
    ]

    operations = [
        CryptoExtension(),
    ]
