"""Encrypted EmailField  added in user model"""
# Generated by Django 3.1.1 on 2020-11-08 17:44


from django.db import migrations
import pgcrypto.fields


class Migration(migrations.Migration):
    """Encrypted Email added postgres"""

    dependencies = [
        ('users', '0003_auto_20201105_0100'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='email',
            field=pgcrypto.fields.EncryptedEmailField(
                charset='utf-8', check_armor=True, cipher='aes',
                unique=True, verbose_name='Email Address', versioned=False),
        ),
    ]
